- name: install grid and pool account setting
  hosts: all
  vars_files:
    - vars/main.yml
  roles:
    - role: geonmo.grid
      grid_middleware: "OSG"
      grid_dummy_host_certificate: true
      grid_site_name: "KR-DUMMY-Tier3"
      grid_dummy_ca:
        crt: dummy/CA.crt
        key: dummy/CA.key
        hash: 19d25ae9
        cn: /C=KR/O=KISTI/O=GSDC/O=Dummy CA/CN=
      ca_info:
        cn: /C=KR/O=KISTI/O=GSDC/CN=Dummy CA
        target: /C=KR/O=KISTI/O=GSDC/*
