- name: Install htcondor-ce package
  hosts: condor_ce
  vars:
    grid_vos:
      - cms
    grid_dummy_host_certificate: true
    grid_site_name: "KR-DUMMY-Tier3"
    grid_dummy_ca:
      crt: dummy/CA.crt
      key: dummy/CA.key
      hash: 19d25ae9
      cn: /C=KR/O=KISTI/O=GSDC/O=Dummy CA/CN=
    grid_host_certificate: {}
    ca_info:
      cn: /C=KR/O=KISTI/O=GSDC/CN=Dummy CA
      target: /C=KR/O=KISTI/O=GSDC/*
  roles:
    - role: hephyvienna.grid
    - role: hephyvienna.htcondor_ce
      htcondor_ce_batch_system: condor
      htcondor_ce_argus_server: node3.intranet.local
      htcondor_ce_uid_domain: "{{ ansible_domain }}"
    - role: geonmo.ansible_htcondor
      condor_admin: "admin@node0.intranet.local"
      condor_daemon_list: "MASTER, SCHEDD"
      condor_domain: "intranet.local"
      condor_host: "node1.intranet.local"
      condor_name: "HTCondor Cluster"
      enable_dynamicslot: true
  tasks:
    - template:
        src: dummy.signing_policy.j2
        dest: "/etc/grid-security/certificates/{{ grid_dummy_ca.hash }}.signing_policy"
