- name: Install apel packages from apel github for apelparser
  vars_files: 
    - vars/main.yml
  hosts: condor_ce
  tasks:
    - yum: 
        name: 
          - 'https://github.com/apel/apel/releases/download/1.8.2-1/apel-lib-1.8.2-1.el7.noarch.rpm'
          - 'https://github.com/apel/apel/releases/download/1.8.2-1/apel-parsers-1.8.2-1.el7.noarch.rpm'
          - 'https://github.com/apel/apel/releases/download/1.8.2-1/apel-client-1.8.2-1.el7.noarch.rpm'
        state: present
    - yum:
        name: htcondor-ce-apel
        state: present
    - template:
        src: templates/parser.cfg.j2
        dest: /etc/apel/parser.cfg
        mode: 0600
    - copy:
        src: files/accountingRun.sh
        dest: /etc/cron.daily/accountingRun.cron
    - lineinfile: 
        path: /etc/condor-ce/config.d/50-ce-apel.conf 
        line: "APEL_SCALING_ATTR = 1.0"

 
         
        

- name: Install apel packages from apel github for apelclient
  vars_files: 
    - vars/main.yml
  hosts: apelclient
  tasks:
    - yum:
        name: 
          - 'https://github.com/apel/apel/releases/download/1.8.2-1/apel-lib-1.8.2-1.el7.noarch.rpm'
          - 'https://github.com/apel/apel/releases/download/1.8.2-1/apel-client-1.8.2-1.el7.noarch.rpm'
          - 'mariadb-server'
        state: present
    - service:
        name: mariadb
        state: started
        enabled: true
    - mysql_db:
        name: apelclient
        state: import
        target: /usr/share/apel/client.sql
    - mysql_user:
        name: apel
        host: "{{ item }}"
        state: present
        password: "{{ apeldb_pw }}"
        priv: "apelclient.*:ALL,GRANT"
      with_items:
        - "localhost"
        - "%"
    - template:
        src: templates/client.cfg.j2
        dest: /etc/apel/client.cfg
        mode: 0600
    - template:
        src: templates/sender.cfg.j2
        dest: /etc/apel/sender.cfg
    - copy:
        src: files/accountingSend.sh
        dest: /etc/cron.daily/accountingSend.cron

