- name: Install apel packages from apel github
  vars_files: 
    - vars/main.yml
  hosts: condor_ce
  tasks:
    - yum: 
        name: 'https://github.com/apel/apel/releases/download/1.8.2-1/apel-lib-1.8.2-1.el7.noarch.rpm'
        state: present
    - yum: 
        name: 'https://github.com/apel/apel/releases/download/1.8.2-1/apel-parsers-1.8.2-1.el7.noarch.rpm'
        state: present
    - yum: 
        name: 'https://github.com/apel/apel/releases/download/1.8.2-1/apel-client-1.8.2-1.el7.noarch.rpm'
        state: present
    - yum:
        name: htcondor-ce-apel
        state: present
    - template:
        src: templates/parser.cfg.j2
        dest: /etc/apel/parser.cfg
        

