- name: install epel
  hosts: all
  roles:
    - role: geerlingguy.repo-epel

- name: grid and pool account setting
  hosts: all
  vars:
    poolaccounts:
      - name: 'cms%03d'
        uid: 10000
        number: 2
        step: 2
        description: 'Standard User of the CMS VO'
        group: cms
        gid: 10000
      - name: 'cmsprd%02d'
        uid: 11000
        number: 2
        step: 2
        description: 'Production User of the CMS VO'
        group: cmsprd
        gid: 11000
        groups: cms
      - name: 'cmspil%02d'
        uid: 12000
        number: 2
        step: 2
        description: 'Pilot User of the CMS VO'
        group: cmspil
        gid: 12000
        groups: cms
      - name: 'cmssgm'
        uid: 13000
        description: 'SW User of the CMS VO'
        group: cmssgm
        gid: 13000
        groups: cms
    grid_vos:
      - cms
  roles:
    - role: hephyvienna.grid
    - role: hephyvienna.poolaccounts

- name: Install htcondor-ce package
  hosts: condor_ce
  vars:
    grid_vos:
      - cms
    grid_site_name:
      - "demo_site"
  roles:
    - role: hephyvienna.grid
    - role: hephyvienna.htcondor_ce
      htcondor_ce_batch_system: condor
      htcondor_ce_argus_server: node3.intranet.local
      htcondor_ce_uid_domain: "{{ ansible_domain }}"
    - role: geonmo.ansible_htcondor
      condor_admin: "admin@node0.intranet.local"
      condor_daemon_list: "MASTER, SCHEDD"
      condor_domain: "intranet.local"
      condor_host: "node1.intranet.local"
      condor_name: "HTCondor Cluster"
      enable_dynamicslot: true


- name: Setup local condor(LRMS) collector
  hosts: lrms
  vars:
    grid_vos:
      - cms
    grid_umd_repo_exclude:
      - dpm-*
      - lfc-*
      - lcgdm-*
  roles:
    - role: hephyvienna.grid
    - role: hephyvienna.workernode
      workernode_ui: true
      worknode_install_htc_ce_client: true
    - role: geonmo.ansible_htcondor
      condor_admin: "admin@node0.intranet.local"
      condor_daemon_list: "MASTER, COLLECTOR, NEGOTIATOR"
      condor_domain: "intranet.local"
      condor_host: "node1.intranet.local"
      condor_name: "HTCondor Cluster"

- name: Setup local condor WN
  hosts: condor_wn
  vars:
    grid_vos:
      - cms
    grid_umd_repo_exclude:
      - dpm-*
      - lfc-*
      - lcgdm-*
  roles:
    - role: hephyvienna.grid
    - role: hephyvienna.workernode
      workernode_ui: false
      worknode_install_htc_ce_client: false
    - role: geonmo.ansible_htcondor
      condor_admin: "admin@node0.intranet.local"
      condor_daemon_list: "MASTER, STARTD"
      condor_domain: "intranet.local"
      condor_host: "node1.intranet.local"
      condor_name: "HTCondor Cluster"
      enable_dynamicslot: true
